import { Inter } from '@next/font/google'
import Head from 'next/head'
import Contact from '../src/Components/Contact/Contact'
import Footer from '../src/Components/Footer/Footer'
import Hero from '../src/Components/Hero/Hero'
import Navbar from '../src/Components/Navbar/Navbar'
import ProjectShowcase from '../src/Components/Project/ProjectShowcase'
import Review from '../src/Components/Review/Review'
import Services from '../src/Components/Services/Services'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar/>
      </nav>
      <main>
        <Hero/>
        <Services/>
        <ProjectShowcase/>
        <Review/>
        <Contact/>
        <Footer/>
      </main>
    </>
  )
}
